name:                ddhc-scanner
version:             0.1.0.0
license:             BSD3
author:              "hasklix"
maintainer:          "_not_@_disclosed_._out_"
copyright:           "2021 hasklix"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Scanner/Lexer for DDHC (Drastically Different Haskell Compiler)
category:            Compiler/Interpreter

description:         No description for now :)

dependencies:
- base >= 4.7 && < 5
- ddlewd >= 0.1.0.0

executables:
  ddhc-scanner:
    source-dirs:      app
    main:             Main.hs
    dependencies:
    - ddhc-scanner
    # ghc-options:
    # - -fhpc

library:
  source-dirs: src
  ghc-options:
  - -Wall
  # - -fhpc
  default-extensions:
  - NoImplicitPrelude

tests:
  ddhc-scanner-tests:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - NoImplicitPrelude
    dependencies:
    - ddlewd
    - ddhc-scanner
    - hspec
