name:                ddhc-parser
version:             0.1.0.0
synopsis:            Parser for DDHC (Drastically Different Haskell Compiler)
#description:
#homepage:            
license:             BSD3
author:              hasklix
maintainer:          _not_@_disclosed_._out_
copyright:           2021 hasklix
category:            Parser
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - ddlewd
  - ddhc-scanner

library:
  source-dirs: src
  ghc-options:
  - -Wall
  # - -fhpc
  default-extensions:
  - NoImplicitPrelude

executables:
  ddhc-parser:
    source-dirs:      app
    main:             Main.hs
    default-extensions:
    - NoImplicitPrelude
    dependencies:
    - ddhc-parser
    # ghc-options:
    # - -fhpc

# tests:
#   ddhc-lexer:
#     main:        Spec.hs
#     source-dirs: test/lexer
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - ddhc-parser
#     - hspec
